name: laravel
recipe: laravel
config:
  webroot: ./public
  php: 8.2
proxy:
  appserver:
    - laravel.localhost
  mailhog:
    - mail.laravel.localhost
services:
  appserver:
    scanner: false
    ssl: false
  database:
    type: mysql
    creds:
      user: username
      password: password
      database: laravel
  node:
    type: node:18
    scanner: false
    ssl: false
    overrides:
      image: node:20
    ports:
      - "5173:5173"
  mailhog:
    type: mailhog
    scanner: false
    portforward: true
tooling:
  node:
    service: node
  yarn:
    service: node
  dev:
    service: node
    cmd: yarn dev
  build:
    service: node
    cmd: yarn build
